### ISSUE TITLE
请问 docker 能搞个直连的么

### ISSUE THREAD

**Issue by cryzlasm** [ykxVK8yL5L/pikpak#2]
我本来有梯子，搞个直连官网的API就挺好， 现在还要给他各种 workers 加梯子，好麻烦的，他这个什么workers 还不稳定

**Comment by xdrghbjiikmdghu** [comment]
> 我本来有梯子，搞个直连官网的API就挺好， 现在还要给他各种 workers 加梯子，好麻烦的，他这个什么workers 还不稳定

建议你看一下我视频里提到的zyplayer版docker 里面的是我自己用的 直连 不用设置代理

**Comment by ykxVK8yL5L** [comment]
> 我本来有梯子，搞个直连官网的API就挺好， 现在还要给他各种 workers 加梯子，好麻烦的，他这个什么workers 还不稳定

看了下 网页版的源码 清空代理设置应该就不用走代理了

**Comment by cryzlasm** [comment]
嗯 清空以后，就不走 worker了，不过会有跨域的问题， 装个 “CORS Unblock” 插件就好了
